"""
visualization.py

Functions for displaying and saving plots generated by WearMatch.
"""

from pathlib import Path

import matplotlib.pyplot as plt
from PIL import Image

from config import FIGURE_DPI


# ==========================================================
# Image Comparison
# ==========================================================

def show_image_comparison(original, resized):
    """
    Display original and resized images side by side.
    """

    fig, ax = plt.subplots(1, 2, figsize=(12, 6))

    ax[0].imshow(original)
    ax[0].set_title(
        f"Original\n{original.size[0]} × {original.size[1]}"
    )
    ax[0].axis("off")

    ax[1].imshow(resized)
    ax[1].set_title(
        f"Downscaled\n{resized.size[0]} × {resized.size[1]}"
    )
    ax[1].axis("off")

    plt.tight_layout()
    plt.show()


# ==========================================================
# Elbow Plot
# ==========================================================

import matplotlib.pyplot as plt


def choose_k_from_plot(ks, distortions):
    """
    Displays the elbow plot and lets the user choose K
    by clicking near one of the points.

    Returns
    -------
    int
        Selected K
    """

    fig, ax = plt.subplots(figsize=(7, 5))

    ax.plot(
        ks,
        distortions,
        marker="o",
        linewidth=2,
        markersize=8
    )

    ax.set_title(
        "Choose K by clicking a point"
    )

    ax.set_xlabel("Number of Clusters (K)")
    ax.set_ylabel("Distortion")

    ax.set_xticks(ks)

    ax.grid(True)

    chosen_k = {"value": None}

    def onclick(event):

        if event.xdata is None:
            return

        x = event.xdata

        nearest = min(
            ks,
            key=lambda k: abs(k - x)
        )

        chosen_k["value"] = nearest

        ax.scatter(
            nearest,
            distortions[nearest - 1],
            s=250,
            color="red",
            zorder=5
        )

        ax.set_title(
            f"Selected K = {nearest}"
        )

        fig.canvas.draw()

        plt.pause(0.6)

        plt.close(fig)

    fig.canvas.mpl_connect(
        "button_press_event",
        onclick
    )

    for x, y in zip(ks, distortions):

        ax.annotate(
            str(x),
            (x, y),
            xytext=(0, 10),
            textcoords="offset points",
            ha="center"
        )

    plt.show()

    return chosen_k["value"]



def save_elbow_plot(
    ks,
    distortions,
    output_folder: Path
):

    plt.figure(figsize=(6, 4))

    plt.plot(
        ks,
        distortions,
        marker="o",
        linewidth=2
    )

    plt.xticks(ks)

    plt.title("Elbow Method")

    plt.xlabel("Number of Clusters")

    plt.ylabel("Distortion")

    plt.grid(True)

    plt.tight_layout()

    plt.savefig(
        output_folder / "elbow_plot.png",
        dpi=FIGURE_DPI
    )

    plt.close()


# ==========================================================
# Average Colour
# ==========================================================

def show_average_color(rgb):
    """
    Displays average colour.
    """

    plt.figure(figsize=(3, 3))

    plt.imshow([[rgb]])

    plt.title("Average Colour")

    plt.axis("off")

    plt.show()


def save_average_color(
    rgb,
    output_folder: Path
):

    image = Image.new(
        "RGB",
        (500, 500),
        rgb
    )

    image.save(
        output_folder / "average_color.png"
    )


# ==========================================================
# Palette
# ==========================================================

def show_palette(palette):
    """
    Displays palette.
    """

    plt.figure(figsize=(10, 2))

    plt.imshow([palette])

    plt.title("Dominant Palette")

    plt.axis("off")

    plt.show()

def show_multiple_palettes(palettes):
    """
    Displays multiple palettes stacked vertically.

    Parameters
    ----------
    palettes : dict

    {
        4 : [(...),(...)]
        5 : ...
        6 : ...
    }
    """

    rows = len(palettes)

    fig, ax = plt.subplots(
        rows,
        1,
        figsize=(10, rows * 2)
    )

    if rows == 1:
        ax = [ax]

    for axes, (k, palette) in zip(ax, palettes.items()):

        axes.imshow([palette])

        axes.set_title(f"K = {k}")

        axes.axis("off")

    plt.tight_layout()

    plt.show()

def save_palette(
    palette,
    output_folder: Path
):

    width = 200 * len(palette)

    image = Image.new(
        "RGB",
        (width, 200)
    )

    for i, colour in enumerate(palette):

        block = Image.new(
            "RGB",
            (200, 200),
            colour
        )

        image.paste(
            block,
            (i * 200, 0)
        )

    image.save(
        output_folder / "palette.png"
    )

def save_multiple_palettes(
    palettes,
    output_folder
):

    for k, palette in palettes.items():

        width = 200 * len(palette)

        image = Image.new(
            "RGB",
            (width, 200)
        )

        for i, colour in enumerate(palette):

            block = Image.new(
                "RGB",
                (200, 200),
                colour
            )

            image.paste(
                block,
                (i * 200, 0)
            )

        image.save(
            output_folder / f"palette_k{k}.png"
        )